<a href="https://colab.research.google.com/github/Sam-013/DS-A-Lab-Tasks/blob/main/20SW013_LAB_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

TASK: 1

In [3]:
import numpy as np
even_num = np.arange(2, 33, 2)
X = even_num.reshape(4, 4)
print(X)


[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


TASK: 2

In [2]:
import numpy as np
X = np.arange(1, 26).reshape(5, 5)
Y = X[X % 2 == 1]
print(X)
print(Y)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25]


TASK: 3

In [1]:
import numpy as np
numbers = np.arange(1, 5)
X = np.zeros((4, 4))
for i in range(4):
    X[:, i] = numbers[i]

print(X)


[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]
